export const GAME_CONFIG = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,

  PLAYER_X: 200,
  PLAYER_START_Y: 300,
  PLAYER_SIZE: 32,

  GRAVITY_Y: 1,
  JUMP_VELOCITY: -10,

  PIPE_WIDTH: 80,
  PIPE_GAP_HEIGHT: 180,
  PIPE_SPEED: 3,
  PIPE_SPAWN_INTERVAL: 1500,

  GROUND_HEIGHT: 80,
  CEILING_HEIGHT: 10,
} as const;
